# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(346, 280)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_folder_path = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_folder_path.setGeometry(QtCore.QRect(10, 30, 261, 20))
        self.lineEdit_folder_path.setObjectName("lineEdit_folder_path")
        self.pushButton_open_folder = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_open_folder.setGeometry(QtCore.QRect(280, 30, 51, 23))
        self.pushButton_open_folder.setObjectName("pushButton_open_folder")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 253, 251, 23))
        self.progressBar.setObjectName("progressBar")
        self.label_process = QtWidgets.QLabel(self.centralwidget)
        self.label_process.setGeometry(QtCore.QRect(10, 250, 251, 31))
        self.label_process.setText("Complete!")
        self.label_process.setObjectName("label_process")
        self.label_process.hide()
        self.listWidget_folder_files = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_folder_files.setGeometry(QtCore.QRect(10, 60, 256, 192))
        self.listWidget_folder_files.setObjectName("listWidget_folder_files")
        self.pushButton_convert = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_convert.setGeometry(QtCore.QRect(270, 250, 75, 23))
        self.pushButton_convert.setObjectName("pushButton_convert")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_open_folder.setText(_translate("MainWindow", "Open"))
        self.pushButton_convert.setText(_translate("MainWindow", "Convert"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
